---

- name: Create group
  iam_group:
    state: present
    name: "{{ all_resources_names[app_name]['iam_group_name'] }}"
    region: "{{ default_region }}"
    managed_policy: ["{{ application_resource_names['ecr_ro_policy']['Arn']}}"]
  register: result

- name: Save off role  information for this application
  set_fact:
    application_resource_names: "{{ application_resource_names | default({}) | combine({item.key: item.value}) }}"
  with_items:
    - { key: "group", value: "{{ result['iam_group'] }}" }

- name: Update global information for all resources
  set_fact:
    all_resources_names: "{{ all_resources_names | default({}) | combine({item.key: item.value}) }}"
  with_items:
    - {key: "{{ app_name }}", value: "{{ application_resource_names }}" }
